"""pr1_foundation

Revision ID: 0394250e44ad
Revises: 28f7f5014a54
Create Date: 2026-02-02 22:49:24.059053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0394250e44ad'
down_revision: Union[str, Sequence[str], None] = '28f7f5014a54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('question_metadata') # Commented out to avoid errors if missing
    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_agent', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('failure_reason', sa.String(), nullable=True))

    with op.batch_alter_table('personal_profiles', schema=None) as batch_op:
        # These columns might already exist if profile table migration ran but schema diff sees them? 
        # Safer to make them nullable=True (which they are).
        batch_op.add_column(sa.Column('first_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('last_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('age', sa.Integer(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('otp_secret', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('last_activity', sa.String(), nullable=True))

    op.create_table('otp_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_otp_codes_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('last_activity')
        batch_op.drop_column('is_2fa_enabled')
        batch_op.drop_column('otp_secret')
        batch_op.drop_column('is_active')

    with op.batch_alter_table('personal_profiles', schema=None) as batch_op:
        batch_op.drop_column('age')
        batch_op.drop_column('last_name')
        batch_op.drop_column('first_name')

    with op.batch_alter_table('login_attempts', schema=None) as batch_op:
        batch_op.drop_column('failure_reason')
        batch_op.drop_column('user_agent')

    op.create_table('question_metadata',
    sa.Column('question_id', sa.INTEGER(), nullable=False),
    sa.Column('source', sa.VARCHAR(), nullable=True),
    sa.Column('version', sa.VARCHAR(), nullable=True),
    sa.Column('tags', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('question_id')
    )
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_otp_codes_user_id'))

    op.drop_table('otp_codes')
    # ### end Alembic commands ###
